/** @type {import('next').NextConfig} */
const nextConfig = {
	env: {
		NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
		NEXT_PUBLIC_ZG_RPC_URL: process.env.NEXT_PUBLIC_ZG_RPC_URL,
		NEXT_PUBLIC_ZG_CHAIN_ID: process.env.NEXT_PUBLIC_ZG_CHAIN_ID,
		NEXT_PUBLIC_AGENT_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_AGENT_REGISTRY_ADDRESS,
		NEXT_PUBLIC_PAYMENT_ROUTER_ADDRESS: process.env.NEXT_PUBLIC_PAYMENT_ROUTER_ADDRESS,
		NEXT_PUBLIC_SPLIT_VAULT_ADDRESS: process.env.NEXT_PUBLIC_SPLIT_VAULT_ADDRESS,
		NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID,
	},
};

export default nextConfig;
